steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: ['run', 'build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        firebase deploy --only functions --project=ees-mobile-5wwwg
