
'use client';

import React from 'react';
import { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import type { UserRole, ManagedUser, Teacher, CoordinatorProfile } from '@/types';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Loader2, Info } from 'lucide-react';
import { useToast } from "@/hooks/use-toast";
import { functions } from '@/lib/firebase'; 
import { httpsCallable, type HttpsCallableResult } from 'firebase/functions'; 
import { Card, CardHeader as UICardHeader, CardContent as UICardContent, CardTitle as UICardTitle } from '@/components/ui/card';

const addUserSchema = z.object({
  name: z.string().min(2, { message: 'Name must be at least 2 characters.' }),
  email: z.string().email({ message: 'This email will be used for login. Ensure it is unique.' }),
  role: z.custom<UserRole>(val => ['Teacher', 'Student', 'Coordinator'].includes(val as UserRole), 'Role is required. Admin role cannot be created here.'),
});

type AddUserFormValues = z.infer<typeof addUserSchema>;

interface AddUserDialogProps {
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
  onUserAdded: (newUser: Partial<ManagedUser & { uid?: string }>) => void; 
}

export function AddUserDialog({ isOpen, onOpenChange, onUserAdded }: AddUserDialogProps) {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [generatedCredentials, setGeneratedCredentials] = useState<{email: string, password: string} | null>(null);
  const { toast } = useToast();

  const form = useForm<AddUserFormValues>({
    resolver: zodResolver(addUserSchema),
    defaultValues: {
      name: '',
      email: '',
      role: 'Student',
    },
  });

  async function onSubmit(values: AddUserFormValues) {
    setIsSubmitting(true);
    setGeneratedCredentials(null);

    const loginEmail = values.email;
    
    try {
      const createUserAccountFunction = httpsCallable(functions, 'createUserAccount');
      const result = await createUserAccountFunction({
        email: loginEmail,
        // Password will be generated by the Cloud Function by default if not sent
        // password: defaultPassword, 
        name: values.name,
        role: values.role,
      }) as HttpsCallableResult<{ success: boolean; message: string; uid: string; generatedPassword?: string }>;

      if (result.data.success) {
        onUserAdded({ id: result.data.uid, name: values.name, email: loginEmail, role: values.role });
        
        const displayedPassword = result.data.generatedPassword || "Default (generated by server)";
        setGeneratedCredentials({ email: loginEmail, password: displayedPassword });
        
        toast({
          title: "User Account Creation Initiated!",
          description: (
            React.createElement('div', null,
              React.createElement('p', null, result.data.message),
              React.createElement('p', {className: "mt-2"}, React.createElement('strong', null, "Login Email: "), loginEmail),
              React.createElement('p', null, React.createElement('strong', null, "Default Password: "), displayedPassword),
              React.createElement('p', {className: "text-xs mt-1 text-destructive"}, "Advise user to change password on first login.")
            )
          ),
          duration: 20000,
        });
      } else {
        throw new Error(result.data.message || "Cloud function reported failure.");
      }
    } catch (error: any) {
      console.error("Error calling createUserAccount function:", error);
      let errMsg = "Could not create user account via Cloud Function.";
      if (error.message) {
        errMsg = error.message;
      }
      if (error.code) { 
        errMsg = `Function Error (${error.code}): ${error.message}`;
      }
      toast({
        title: "Error Adding User",
        description: errMsg,
        variant: "destructive",
      });
    } finally {
      setIsSubmitting(false);
    }
  }

  const handleCloseDialog = () => {
    if (!isSubmitting) {
        form.reset();
        setGeneratedCredentials(null);
        onOpenChange(false);
    }
  };

  useEffect(() => {
    if (!isOpen) {
      form.reset();
      setGeneratedCredentials(null);
    }
  }, [isOpen, form]);

  return (
    <Dialog open={isOpen} onOpenChange={handleCloseDialog}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Add New User Account (via Cloud Function)</DialogTitle>
          <DialogDescription>
            Enter details. The system will create the user's Auth account and Firestore profile(s). Admins must be created manually in Firebase console.
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4 py-4">
            <FormField
              control={form.control}
              name="name"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Full Name</FormLabel>
                  <FormControl>
                    <Input placeholder="e.g. John Doe" {...field} disabled={isSubmitting || !!generatedCredentials}/>
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="email"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Login Email Address</FormLabel>
                  <FormControl>
                    <Input type="email" placeholder="e.g. john.doe@example.com" {...field} disabled={isSubmitting || !!generatedCredentials}/>
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="role"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Role</FormLabel>
                  <Select onValueChange={field.onChange} defaultValue={field.value} disabled={isSubmitting || !!generatedCredentials}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Select a role" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      <SelectItem value="Student">Student</SelectItem>
                      <SelectItem value="Teacher">Teacher</SelectItem>
                      <SelectItem value="Coordinator">Coordinator</SelectItem>
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />

            {generatedCredentials && (
              <Card className="mt-4 p-4 border-green-500 bg-green-50/80 rounded-md text-sm shadow-md">
                <UICardHeader className='p-0 pb-2'>
                  <UICardTitle className="text-md font-semibold text-green-700 flex items-center"><Info className="h-5 w-5 mr-2"/>Credentials Generated</UICardTitle>
                </UICardHeader>
                <UICardContent className='p-0'>
                  <p><span className="font-medium">Login Email:</span> {generatedCredentials.email}</p>
                  <p><span className="font-medium">Default Password:</span> {generatedCredentials.password}</p>
                  <p className="text-xs mt-1 text-destructive">Advise user to change password on first login.</p>
                </UICardContent>
              </Card>
            )}

            <DialogFooter className="pt-4">
                <Button type="button" variant="outline" onClick={handleCloseDialog} disabled={isSubmitting}>
                  {generatedCredentials ? "Close" : "Cancel"}
                </Button>
              {!generatedCredentials && (
                <Button type="submit" disabled={isSubmitting}>
                  {isSubmitting ? (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  ) : null}
                  Create User Account
                </Button>
              )}
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
